services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
    volumes: [ db_data:/var/lib/mysql ]
  wp:
    image: wordpress:php8.2-apache
    ports: [ "8080:80" ]
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
volumes:
  db_data:
